## profile
spring:
  profiles:
    active: ${profile}

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  sql:
    init:
      mode: always
      schema-locations: classpath:sql/schema.sql
